// Post.js - Mongoose model for blog posts

const mongoose = require('mongoose');

const PostSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Please provide a title'],
      trim: true,
      maxlength: [100, 'Title cannot be more than 100 characters'],
    },
    content: {
      type: String,
      required: [true, 'Please provide content'],
    },
    featuredImage: {
      type: String,
      default: 'default-post.jpg',
    },
    // NEW: Multer upload path (e.g., "/uploads/abc123.jpg")
    image: {
      type: String,
    },
    slug: {
      type: String,
      required: false, // Will be auto-generated by pre-save hook
      unique: true,
      sparse: true, // Allow multiple null/empty slugs temporarily
      validate: {
        validator: function(v) {
          // Allow empty during creation, pre-save hook will set it
          return true;
        },
        message: 'Slug is required'
      }
    },
    excerpt: {
      type: String,
      maxlength: [200, 'Excerpt cannot be more than 200 characters'],
    },
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      // Changed: NOT required – allows posts without category
    },
    tags: [String],
    isPublished: {
      type: Boolean,
      default: false,
    },
    viewCount: {
      type: Number,
      default: 0,
    },
    // Embedded comments (kept for instructor compatibility)
    comments: [
      {
        user: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'User',
        },
        content: {
          type: String,
          required: true,
        },
        createdAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],
  },
  { timestamps: true }
);

// Create slug from title before saving
PostSchema.pre('save', function (next) {
  // Always generate slug if it's missing, empty, or title is modified
  const needsSlug = !this.slug || 
                    (typeof this.slug === 'string' && this.slug.trim() === '') || 
                    this.isModified('title');
  
  if (needsSlug) {
    if (this.title && this.title.trim()) {
      let slug = this.title
        .toLowerCase()
        .trim()
        .replace(/[^\w\s-]+/g, '') // Remove special characters except spaces and hyphens
        .replace(/\s+/g, '-') // Replace spaces with hyphens
        .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
        .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
      
      // If slug is empty after processing, use a fallback
      if (!slug || slug.length === 0) {
        slug = 'post-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
      }
      
      this.slug = slug;
    } else {
      // If no title, generate a unique slug
      this.slug = 'post-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
    }
  }
  
  // Ensure slug is never empty or undefined
  if (!this.slug || this.slug.trim() === '') {
    this.slug = 'post-' + Date.now() + '-' + Math.random().toString(36).substr(2, 9);
  }
  
  next();
});

// Virtual for post URL
PostSchema.virtual('url').get(function () {
  return `/posts/${this.slug}`;
});

// Method to add a comment (embedded)
PostSchema.methods.addComment = function (userId, content) {
  this.comments.push({ user: userId, content });
  return this.save();
};

// Method to increment view count
PostSchema.methods.incrementViewCount = function () {
  this.viewCount += 1;
  return this.save();
};

module.exports = mongoose.model('Post', PostSchema);